# Generated by Django 5.0.1 on 2024-01-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('transaction_mode', models.CharField(choices=[('online', 'ONLINE'), ('cash', 'CASH'), ('credit_card', 'CREDIT_CARD')], max_length=15)),
                ('expense_for', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_category_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('expense_subcategory_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.expense_category')),
                ('expense_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.expense_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('transaction_mode', models.CharField(choices=[('online', 'ONLINE'), ('cash', 'CASH')], max_length=20)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.income_category')),
            ],
        ),
    ]
