# Generated by Django 5.0.1 on 2024-01-30 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Expense Category',
            },
        ),
        migrations.CreateModel(
            name='Income_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Income Category',
            },
        ),
        migrations.CreateModel(
            name='Expense_Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.expense_category')),
            ],
            options={
                'verbose_name_plural': 'Expense Subcategory',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('transaction_mode', models.CharField(choices=[('online', 'ONLINE'), ('cash', 'CASH'), ('credit_card', 'CREDIT_CARD')], max_length=15)),
                ('expense_for', models.CharField(choices=[('self', 'SELF'), ('spouse', 'SPOUSE'), ('childern', 'CHILDERN'), ('parents', 'PARENTS'), ('in-laws', 'IN-LAWS'), ('siblings', 'SIBLINGS'), ('friends', 'FRIENDS'), ('others', 'OTHERS')], max_length=20)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_category_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('expense_subcategory_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.expense_category')),
                ('expense_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.expense_subcategory')),
            ],
            options={
                'verbose_name_plural': 'Expense',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('transaction_mode', models.CharField(choices=[('online', 'ONLINE'), ('cash', 'CASH')], max_length=20)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_manager.income_category')),
            ],
            options={
                'verbose_name_plural': 'Income',
            },
        ),
    ]
