# Generated by Django 5.0.1 on 2024-01-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='expense_category',
            options={'verbose_name_plural': 'Expense Category'},
        ),
        migrations.AlterModelOptions(
            name='expense_subcategory',
            options={'verbose_name_plural': 'Expense Subcategory'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name_plural': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='income_category',
            options={'verbose_name_plural': 'Income Category'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_for',
            field=models.CharField(choices=[('self', 'SELF'), ('spouse', 'SPOUSE'), ('childern', 'CHILDERN'), ('parents', 'PARENTS'), ('in-laws', 'IN-LAWS'), ('siblings', 'SIBLINGS'), ('friends', 'FRIENDS'), ('others', 'OTHERS')], max_length=20),
        ),
    ]
