# Generated by Django 5.0.1 on 2024-01-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0002_alter_expense_options_alter_expense_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_subcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='money_manager.expense_category'),
            preserve_default=False,
        ),
    ]
